kafka:
  pool: nav-dev
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
ingress:
  url: https://tiltakspenger-vedtak.intern.dev.nav.no
cluster: dev-gcp
tenant: trygdeetaten.no
urlPdl: pdl-api.dev-fss-pub.nais.io
urlSkjerming: skjermede-personer-pip.intern.dev.nav.no
azure:
  groups:
    - name: ROLE_SAKSBEHANDLER
      id: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
    - name: ROLE_BESLUTTER
      id: 79985315-b2de-40b8-a740-9510796993c6
    - name: ROLE_FORTROLIG
      id: ea930b6b-9397-44d9-b9e6-f4cf527a632a
    - name: ROLE_STRENGT_FORTROLIG
      id: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
    - name: ROLE_SKJERMING
      id: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
    - name: ROLE_DRIFT
      id: c511113e-5b22-49e7-b9c4-eeb23b01f518
