sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840
ingress:
  url: https://tiltakspenger-vedtak.intern.nav.no
cluster: prod-gcp
tenant: nav.no
urlPdl: pdl-api.prod-fss-pub.nais.io
urlSkjerming: skjermede-personer-pip.intern.nav.no
urlJoark: dokarkiv.prod-fss-pub.nais.io
urlDokdist: dokdistfordeling.prod-fss-pub.nais.io
azure:
  groups:
    - name: ROLE_SAKSBEHANDLER
      id: 6c6ce2e8-b2e2-4c4b-8194-215c8e27a5c7
    - name: ROLE_BESLUTTER
      id: de518927-f657-4f37-9a64-14fdfd968dd2
    - name: ROLE_FORTROLIG
      id: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: ROLE_STRENGT_FORTROLIG
      id: ad7b87a6-9180-467c-affc-20a566b0fec0
    - name: ROLE_SKJERMING
      id: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    - name: ROLE_DRIFT
      id: 0405ed09-1248-47f7-a6e3-e998bc90feca
