apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-vedtak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      claims:
        groups:
        {{#each azure.groups}}
          - id: {{this.id}}
        {{/each}}
        extra:
          - NAVident
          - azp_name
  leaderElection: true
  gcp:
    sqlInstances:
      - name: tiltakspenger-vedtak
        type: POSTGRES_15
        tier: {{ sqlInstances.tier }}
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: vedtak
            envVarPrefix: DB
            users:
              - name: tpts_ds
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-tiltak
        - application: tiltakspenger-pdfgen
        - application: utsjekk
          namespace: helved
      external:
        - host: {{ urlPdl }}
        - host: {{ urlPdlPip }}
        - host: {{ urlSkjerming }}
        - host: {{ urlJoark }}
        - host: {{ urlDokdist }}
        - host: {{ urlMicrosoftGraphApi }}
    inbound:
      rules:
        - application: tiltakspenger-saksbehandler
          namespace: tpts
          cluster: {{ cluster }}
        - application: tiltakspenger-datadeling
          namespace: tpts
          cluster: {{ cluster }}
          permissions:
            roles:
              - "hente_data"
        - application: tiltakspenger-soknad-api
          namespace: tpts
          cluster: {{ cluster }}
          permissions:
            roles:
              - "lage_hendelser"
  env:
  {{#each azure.groups}}
    - name: {{this.name}}
      value: {{this.id}}
  {{/each}}
