apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-vedtak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      claims:
        groups:
          - id: {{ ROLE_SAKSBEHANDLER }}
          - id: {{ ROLE_FORTROLIG }}
          - id: {{ ROLE_STRENGT_FORTROLIG }}
          - id: {{ ROLE_SKJERMING }}
        extra:
          - NAVident
          - azp_name
  gcp:
    sqlInstances:
      - name: tiltakspenger-vedtak
        type: POSTGRES_14
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        databases:
          - name: vedtak
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-flate
          namespace: tpts
          cluster: {{ cluster }}
